package com.example.textrxretrofit.entity.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.textrxretrofit.entity.bean.Gun;

import com.example.textrxretrofit.entity.dao.GunDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gunDaoConfig;

    private final GunDao gunDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gunDaoConfig = daoConfigMap.get(GunDao.class).clone();
        gunDaoConfig.initIdentityScope(type);

        gunDao = new GunDao(gunDaoConfig, this);

        registerDao(Gun.class, gunDao);
    }
    
    public void clear() {
        gunDaoConfig.clearIdentityScope();
    }

    public GunDao getGunDao() {
        return gunDao;
    }

}
