package com.example.testgreendao.entity.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.testgreendao.entity.bean.Gun;
import com.example.testgreendao.entity.bean.GunData;
import com.example.testgreendao.entity.bean.Score;
import com.example.testgreendao.entity.bean.Student;
import com.example.testgreendao.entity.bean.StudentScore;
import com.example.testgreendao.entity.bean.User;

import com.example.testgreendao.entity.dao.GunDao;
import com.example.testgreendao.entity.dao.GunDataDao;
import com.example.testgreendao.entity.dao.ScoreDao;
import com.example.testgreendao.entity.dao.StudentDao;
import com.example.testgreendao.entity.dao.StudentScoreDao;
import com.example.testgreendao.entity.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gunDaoConfig;
    private final DaoConfig gunDataDaoConfig;
    private final DaoConfig scoreDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig studentScoreDaoConfig;
    private final DaoConfig userDaoConfig;

    private final GunDao gunDao;
    private final GunDataDao gunDataDao;
    private final ScoreDao scoreDao;
    private final StudentDao studentDao;
    private final StudentScoreDao studentScoreDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gunDaoConfig = daoConfigMap.get(GunDao.class).clone();
        gunDaoConfig.initIdentityScope(type);

        gunDataDaoConfig = daoConfigMap.get(GunDataDao.class).clone();
        gunDataDaoConfig.initIdentityScope(type);

        scoreDaoConfig = daoConfigMap.get(ScoreDao.class).clone();
        scoreDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        studentScoreDaoConfig = daoConfigMap.get(StudentScoreDao.class).clone();
        studentScoreDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        gunDao = new GunDao(gunDaoConfig, this);
        gunDataDao = new GunDataDao(gunDataDaoConfig, this);
        scoreDao = new ScoreDao(scoreDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        studentScoreDao = new StudentScoreDao(studentScoreDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Gun.class, gunDao);
        registerDao(GunData.class, gunDataDao);
        registerDao(Score.class, scoreDao);
        registerDao(Student.class, studentDao);
        registerDao(StudentScore.class, studentScoreDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        gunDaoConfig.clearIdentityScope();
        gunDataDaoConfig.clearIdentityScope();
        scoreDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        studentScoreDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public GunDao getGunDao() {
        return gunDao;
    }

    public GunDataDao getGunDataDao() {
        return gunDataDao;
    }

    public ScoreDao getScoreDao() {
        return scoreDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StudentScoreDao getStudentScoreDao() {
        return studentScoreDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
