package com.example.testgreendao.entity.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.testgreendao.entity.bean.User;

import com.example.testgreendao.entity.bean.GunData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GUN_DATA".
*/
public class GunDataDao extends AbstractDao<GunData, Long> {

    public static final String TABLENAME = "GUN_DATA";

    /**
     * Properties of entity GunData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GunName = new Property(1, String.class, "gunName", false, "gun_name");
        public final static Property GunNo = new Property(2, String.class, "gunNo", false, "gun_no");
        public final static Property HanderName = new Property(3, String.class, "handerName", false, "hander_name");
        public final static Property HanderNo = new Property(4, String.class, "handerNo", false, "hander_no");
        public final static Property UserId = new Property(5, Long.class, "userId", false, "user_id");
    }

    private DaoSession daoSession;


    public GunDataDao(DaoConfig config) {
        super(config);
    }
    
    public GunDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GUN_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"gun_name\" TEXT," + // 1: gunName
                "\"gun_no\" TEXT," + // 2: gunNo
                "\"hander_name\" TEXT," + // 3: handerName
                "\"hander_no\" TEXT," + // 4: handerNo
                "\"user_id\" INTEGER);"); // 5: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GUN_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GunData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String gunName = entity.getGunName();
        if (gunName != null) {
            stmt.bindString(2, gunName);
        }
 
        String gunNo = entity.getGunNo();
        if (gunNo != null) {
            stmt.bindString(3, gunNo);
        }
 
        String handerName = entity.getHanderName();
        if (handerName != null) {
            stmt.bindString(4, handerName);
        }
 
        String handerNo = entity.getHanderNo();
        if (handerNo != null) {
            stmt.bindString(5, handerNo);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(6, userId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GunData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String gunName = entity.getGunName();
        if (gunName != null) {
            stmt.bindString(2, gunName);
        }
 
        String gunNo = entity.getGunNo();
        if (gunNo != null) {
            stmt.bindString(3, gunNo);
        }
 
        String handerName = entity.getHanderName();
        if (handerName != null) {
            stmt.bindString(4, handerName);
        }
 
        String handerNo = entity.getHanderNo();
        if (handerNo != null) {
            stmt.bindString(5, handerNo);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(6, userId);
        }
    }

    @Override
    protected final void attachEntity(GunData entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GunData readEntity(Cursor cursor, int offset) {
        GunData entity = new GunData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // gunName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // gunNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // handerName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // handerNo
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GunData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGunName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGunNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHanderName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHanderNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GunData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GunData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GunData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM GUN_DATA T");
            builder.append(" LEFT JOIN db_user T0 ON T.\"user_id\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GunData loadCurrentDeep(Cursor cursor, boolean lock) {
        GunData entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User mUser = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setMUser(mUser);

        return entity;    
    }

    public GunData loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GunData> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GunData> list = new ArrayList<GunData>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GunData> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GunData> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
