package com.example.testgreendao.entity.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.testgreendao.entity.bean.StudentScore;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "db_student_score".
*/
public class StudentScoreDao extends AbstractDao<StudentScore, Long> {

    public static final String TABLENAME = "db_student_score";

    /**
     * Properties of entity StudentScore.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StudentId = new Property(1, Long.class, "studentId", false, "student_id");
        public final static Property ScoreId = new Property(2, Long.class, "scoreId", false, "score_id");
    }


    public StudentScoreDao(DaoConfig config) {
        super(config);
    }
    
    public StudentScoreDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"db_student_score\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"student_id\" INTEGER," + // 1: studentId
                "\"score_id\" INTEGER);"); // 2: scoreId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"db_student_score\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StudentScore entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindLong(2, studentId);
        }
 
        Long scoreId = entity.getScoreId();
        if (scoreId != null) {
            stmt.bindLong(3, scoreId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StudentScore entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindLong(2, studentId);
        }
 
        Long scoreId = entity.getScoreId();
        if (scoreId != null) {
            stmt.bindLong(3, scoreId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StudentScore readEntity(Cursor cursor, int offset) {
        StudentScore entity = new StudentScore( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // studentId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // scoreId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StudentScore entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStudentId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setScoreId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StudentScore entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StudentScore entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StudentScore entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
